language: go
sudo: required
services:
- docker
notifications:
  email: true
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: "ZC+Hb6wJe17HNbKlPQ8kxMVh1Kvi0SVUt5AucgyKX7pwCy4xFQA02X0CAA/QoUEaMoAkvEy1rPYbLK9dhpSh0lh0h586VIV6IInn4UTaSp9zEXRnsF7jyUwFIMhNrB7VJ+XZYfuc+dd1Ku8ttN6RV5Zq06ixd5q10RspbuUqiicSNx2yFPflk4yvZw/VE70udWyK+6uSry7RjkLcJdUel0U9u5+40LnR0U8db9nY9meJwBsLiiKQfWgEW3WIJv1QuVaFu7gIbeVcj9yb/Syt4+DHkMiTdSZasMEmcALg1gZDNriD5TtmW4966RqzRt+P9K+e4ouOnuVJGaaM6u2qDOht1iwaSyPODpn7zQeAr3AdRMWjmIHpTA6AQxlzubsQ/pHqUwOKVaK/CV/kS+gk1ilFsUqM3tEL4mLP1iQwEuymFT6PkJ6hz0vPddwIJfKDAA5QNLp2GhGTj5c0PwPC9TYOUKyQJVnxsWewLMdlGG52YH5W4JBY0sjq7FOrD24yi8fUL3zQI3iZbbD63RKH1PLZeUVRr8UyvtegPFae4ugCCpfMelE4wfOMjHHnwMMNrorPtVySGTdKpQrdC401Z2j8oR0Jt6s0WjzuxMv36R5hS0ERWNQp8Zh10OLB1vNy73C8fS0NBn/zDWCoTdikLzEhH/40sKTFky3TdMx6oyk="
  - secure: "ccr4q1pfmFnCr5wQZ9mouhMlzmbnukX/UAkXieaZXMm5bzrjXLdYAaOCBsgdonLSHIU2A0uoblXWDSgUyLvSpaNttxofUH1a4yVEwSSpQpso2oB6ECGDJQHQEgF/9TtjS3P9HeADU8WDYLGBOKLpv7e/2eqfMNZ4ZLS8i9cFYo6sNBvl7pJa8GQni6uxB77vPkJ3KShNrSLYI2cCzSBRtLOZa3xsj6GBh0PebAfyzBe308bKuq3RraOz3VS4eF9KYJS1LEBVJNfkyP21Ay+tzGNropcFVWdUN/TaGeaHqY6H1lEXlSZvnBY3zE94i7Mgi33DEej0wsRy5wfVKkbRGksHCkC1vfyonbKeQeCirHkVOmjqCFLAbrc7KNNaxwmss27p6Ctw1e6HTmbQgFqiqi+wugBOJM0AHy40y/5AtECCwBRHTs/flwAU9vrPt1nAD+cxvlxPOEyOAmrFOi0H7whAxM3cPZ/DjJ5CCP9cwpL4h1EDh7+ImEf0Y4dJGQ2SL6pkMgnd2LDlpsDJBS7z5gggTv8Z9w60wIAdpADnoNUKhRDj7AsShJpdHpswD4xnsw9WjPMYmms6fAQSzMERp4cSiPfqOXJcrvA0/9nX/3q4WVZkDRfchHQYTTnUT6VVt7v6bASi7aifbeJ8plezTCIDExbGIZZK9xR15feFtTo="
go:
- 1.7.4
install:
- go get github.com/golang/lint/golint
script:
- go build -v
- go vet $(go list ./... | grep -v vendor)
- test -z "$(golint ./... | grep -v vendor | tee /dev/stderr)"
- test -z "$(gofmt -s -l . | grep -v vendor | tee /dev/stderr)"
- make release
after_success:
- docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
- echo $DOCKER_PASS
- export REPO=smalldave/weather
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
