language: go
sudo: required
services:
- docker
notifications:
  email: true
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: O5n5NsdBcMBrZhoJ8U2jLopcnLXi0Q7PmoZh6dHVmh2a9wKphvXf9PlYC0oyZ+uW2I+qemNX5aA+3SDov3dKNcaJkV738aDb6lXVwW3ga3mW1HDIaGbZz0XuejNTgPt91m/Ih5e2vMOhee72AvIbGq22llkwm254Bifbo0NHaNuR1YmPQeU4lgzup++qmGUEnXroofzkEgFjte1/BJsQzWJBH8Jhe3/a5k9EtMtO1p9rvt5C4/nC50ci3Q7+/wWN6yqFy5+bqtHinsfs0eS5CSLKulSSm5+97jr4oyaDPewyHvg4N3re55cq+mGTQnb7OAhFDCnML0oCzoMlvn23hftV5QrqQQbT+xlR2U343WXg6phyrqZg5IlFJpCCmkCx+abgvMtT5xy21zVnZ8m8GYt7DEHOYJ61z0pp1TEyVaTlOunU7awNMLRufA+zh9PguKTc/zTy4hig3NZyCGa5sLj/H6WTB6girJiLPDubfFrLpl0ylnR2jDCAe8ubf77qO+nAlG1SEwdscGXHfSaZJZIrQXbAejngsNMr7vDVQmVxQwDEWMAEUpvQY+s9/FjzIhDVHtvZJAcoXb0rxGHL3GHf4mpmxURIFJupvIIkPTsErzQzKiIzOIJU+BJsezwTWojmAlW3H7RDceKfWarZA1B8YXPSvitlXWAwMEX8lhw=
  - secure: bbPF+nrVr/YqyPlyuvfLDRFYq/E5HrdAHYZwEJL/kJxnmVTe3II/SIEpDYf78HshqRQLjztrudnWkD9LW3h04yUt5YFmmZegYlxahXAM7W1M5rTUmkfyVMQRZstrqt3a9KG2DtLFeBKgjI24ZFqqhScnyHwpzzAH8O+SQ9DVDUHEPQhSI9YdBunR1qWSFtuSXVaOvgEB6BabiQLMO2J6e90akqEa4E2dsomAy+1w1HSmpz/xO/khbkIotfXpRC848lQ8wBDgdFI23IFg7GDn9IPE1DLiUOq8wPiOzmY1vtrUUT0Pyrx0QE/okJDcnxF6Nf5pxI6MZlqgy6P7jthU6en6Vy8ON9r5mk+38MQPKoK8AmASw2S2FNIaeJNt8SkLkWRK+mDM3FAAChpIdxZH7Eip3hnwON10P2oAS5BAclqBZIQaao3SvVri3Va222laYTXiLSMsfl/23V7JG6UWlbHhP4/ETw6jok+dLIeYqT+ZIWQHcNzA98W9WFQ7uK47kFVinWzA009wLGerZyoLSY8+n6KE1q+6tVldq/dx/+2TOdSqYj/+Sd7Fw5mYabz3Y2Cm8LiI/lmi5Md3NVwUZLCRSzkrgxk6tcg00cuLfzLsh+SqWHR2X34ggNV/clr5aXBfwz5ohpbK3tD72b5LvbOWLCb3Ra2QAS/OfKgvqAA=
go:
- 1.7.4
install:
- go get github.com/golang/lint/golint
script:
- go build -v
- go vet $(go list ./... | grep -v vendor)
- test -z "$(golint ./... | grep -v vendor | tee /dev/stderr)"
- test -z "$(gofmt -s -l . | grep -v vendor | tee /dev/stderr)"
- make release
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=smalldave/weather
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
